### ISSUE TITLE
Unable to install because of problem with preinstall script

### ISSUE THREAD

**Issue by BjornRombaut** [ahmednuaman/grunt-scss-lint#102]
11877 error grunt-scss-lint@0.3.5 preinstall: `bundle`
11877 error Exit status 127
11878 error Failed at the grunt-scss-lint@0.3.5 preinstall script.
11878 error This is most likely a problem with the grunt-scss-lint package,
11878 error not with npm itself.
11878 error Tell the author that this fails on your system:
11878 error     bundle
11878 error You can get their info via:
11878 error     npm owner ls grunt-scss-lint

**Comment by ahmednuaman** [comment]
So do you have `bundle` installed?

**Comment by BjornRombaut** [comment]
is bundle necessary? We used your scss linter before without installing bundle.
You're talking about this one right (https://docs.npmjs.com/cli/bundle) ?

Thanks for the quick response!

**Comment by ahmednuaman** [comment]
Hmm, it shouldn't be, but it is _preferred_ (http://bundler.io/). Pushed v0.3.6 just now.

**Comment by BjornRombaut** [comment]
great, thanks for the update!
