### ISSUE TITLE
npm install fails 0.3.6 fails

### ISSUE THREAD

**Issue by MaryBartlett** [ahmednuaman/grunt-scss-lint#103]
I get this output when trying to npm install 0.3.6. 0.3.5 does the same too. 0.3.4 works ok.

Running npm install --save-dev --save-exact grunt-scss-lint works ok, it's only when it's being installed from package.json.

> grunt-scss-lint@0.3.5 preinstall /home/mbartlet/code/app/node_modules/grunt-scss-lint
> bundle
'''
sh: 1: bundle: not found
npm ERR! grunt-scss-lint@0.3.5 preinstall: `bundle`
npm ERR! Exit status 127
npm ERR! 
npm ERR! Failed at the grunt-scss-lint@0.3.5 preinstall script.
npm ERR! This is most likely a problem with the grunt-scss-lint package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     bundle
npm ERR! You can get their info via:
npm ERR!     npm owner ls grunt-scss-lint
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.13.0-37-generic
npm ERR! command "/home/mbartlet/.nvm/v0.10.32/bin/node" "/home/mbartlet/.nvm/v0.10.32/bin/npm" "install"
npm ERR! cwd /home/mbartlet/code/app
npm ERR! node -v v0.10.32
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0
'''

**Comment by ahmednuaman** [comment]
That looks like it's installing 0.3.5.

**Comment by MaryBartlett** [comment]
true, I hadn't noticed that! I'll delete the cache and try again

**Comment by ahmednuaman** [comment]
Cool :+1:

**Comment by MaryBartlett** [comment]
Much better now :) thanks
