### ISSUE TITLE
JSON formatter from scss lint is not used?

### ISSUE THREAD

**Issue by DBaker85** [ahmednuaman/grunt-scss-lint#106]
Hello,

I was wondering is there a specific reason to not use the JSON formatter available in the scss-lint gem? 

It would be really useful for example if you use the json output to render to custom jade templates.

**Comment by ahmednuaman** [comment]
I haven't needed it, but it'll be very simple to implement so happy if you want to do a PR.

**Comment by DBaker85** [comment]
Alright, I'll give it a shot.

**Comment by ahmednuaman** [comment]
:+1:
