### ISSUE TITLE
Support checkstyle report output

### ISSUE THREAD

**Issue by ngeor** [ahmednuaman/grunt-scss-lint#108]
scss-lint supports generating a checkstyle report, with an extra gem (scss_lint_reporter_checkstyle).

Since grunt-scss-lint does not support that, I can't use grunt-scss-lint in Jenkins. Instead as a workaround I run this command:

    scss-lint --require=scss_lint_reporter_checkstyle \
        --format=Checkstyle \
        -o report.checkstyle.xml

I would like grunt-scss-lint to support this too, so that everything in my build process is maintained in grunt.

**Comment by ahmednuaman** [comment]
Sure, feel free to make a PR.

**Comment by ngeor** [comment]
I created a PR but I think the build is failing because the gem scss_lint_reporter_checkstyle is not installed on the CI?

**Comment by ahmednuaman** [comment]
Update the `.travis.yml` doc

**Comment by ngeor** [comment]
I added the gem to the Gemfile, this seems to have fixed it, travis installs it.
It seems that two builds are performed. The first works and my unit test passes. The second one fails due to all sorts of timeouts, not just on my test. Any ideas?

**Comment by ahmednuaman** [comment]
Have you tried running it locally?

**Comment by ngeor** [comment]
Yeah, when I run the unit tests locally they work fine.
Also, they run fine on Travis. If you notice, for every PR it does two builds (I don't know what the second one is for). Maybe you can help?

**Comment by ahmednuaman** [comment]
That's the beauty of travis, where does it fail?

**Comment by haishengwu-okta** [comment]
any progress?

**Comment by ngeor** [comment]
@haishengwu-okta not really, I haven't updated anything for a long time, because I no longer need the feature.
