### ISSUE TITLE
scss-lint was renamed to scss_lint

### ISSUE THREAD

**Issue by justechn** [ahmednuaman/grunt-scss-lint#109]
according to the changelog (https://github.com/brigade/scss-lint/blob/master/CHANGELOG.md) 0.38.0 scss-lint was renamed to scss_lint. Can we get this project updated to reflect the change?

Thanks

**Comment by ahmednuaman** [comment]
So what do you propose?

**Comment by ryanmc2033** [comment]
I could be wrong, but I would assume that any references to scss-lint need to be changed to scss_lint so they will work with the new name.

**Comment by ahmednuaman** [comment]
I think only in the `Gemfile` it'll matter, so the cli will still be `scss-lint`. Silly standards, feel free to make a PR.

**Comment by jonathancalb** [comment]
What is wrong is the update message:

>> 1. Please make sure you have ruby installed: `ruby -v`
>> 2. Install the `scss-lint` gem by running:
>> gem update --system && gem install scss-lint

The gem to install is scss_lint now. The last line should be:
>> gem update --system && gem install scss_lint

**Comment by ahmednuaman** [comment]
Sure, feel free to PR it?

**Comment by justechn** [comment]
I sent you a pull request some time ago but it ran into build problems. I don't know what your specific build is looking for so I don't know how to fix it

https://github.com/ahmednuaman/grunt-scss-lint/pull/112

**Comment by amclin** [comment]
How is this being resolved? No matter what I try (gem install scss-lint or gem install scss_lint) I get the same error from grunt scsslint about checking to make sure ruby and the gem are installed.

**Comment by ahmednuaman** [comment]
Ok, I'll fix this now.

**Comment by ahmednuaman** [comment]
Cor, this is proper scumbag-steve stuff, why rename it to `scss_lint` but keep the executable as `scss-lint`. Srsly. Anyway, pushing new version now.

**Comment by ahmednuaman** [comment]
It's up.
