### ISSUE TITLE
forceWarnings option was never merged?

### ISSUE THREAD

**Issue by FStop** [ahmednuaman/grunt-scss-lint#111]
I was looking into a way to make use of the `warning` and `error` [severities](https://github.com/brigade/scss-lint#severities) that scss-lint provides and came across #68. The PR shows merged, but the discussion indicates that it was somehow reverted and never reintroduced.

Is there a plan to get this going again?

**Comment by FStop** [comment]
Response from @geebru:
>  I welcome anyone with the dev chops to finish it out to do so as I'm not sure when I'll be able to come back to it.

If it's as simple as reintroducing the original code from the PR, I'll give it a shot. If it gets more complicated than that, I'll see if I can get some help from someone on my team.

**Comment by ahmednuaman** [comment]
:+1:
