### ISSUE TITLE
drop ruby gem and use the pure node module sass-lint

### ISSUE THREAD

**Issue by christianhaller** [ahmednuaman/grunt-scss-lint#121]
It would be great, if you could drop the ruby dependency and use the pure node version!
https://github.com/sasstools/sass-lint

**Comment by ahmednuaman** [comment]
Cool...

![image](https://cloud.githubusercontent.com/assets/99223/9630122/f23ad1f4-516f-11e5-97e8-8c76d4ab448a.png)

**Comment by christianhaller** [comment]
I will try it :)

**Comment by varemenos** [comment]
Is this issue really valid?
I believe what you are looking for is [here](https://github.com/sasstools/grunt-sass-lint)

**Comment by ahmednuaman** [comment]
Any news on this?

**Comment by christianhaller** [comment]
You are right guys.
