### ISSUE TITLE
Grunt task does not fail if scss-lint installation by bundler is missing

### ISSUE THREAD

**Issue by webfeature** [ahmednuaman/grunt-scss-lint#122]
For each project i install an project-specific version of scss_lint with the bundler. If i forget to execute `bundle install --path bundler` and run the grunt task `grunt scsslint`. I get following message:

    Running "scsslint" (scsslint) task
    Running scss-lint on scss
     >> 1 file is lint free
     Results have been written to: scss-lint-report.xml

I also have a global version of scss_lint installed. When i delete the global gem everything is working fine. When i have installed both, a global and project-specific (with bundler) version, i get the lint free message, although errors are included in my scss files.

**Comment by ahmednuaman** [comment]
Fancy creating a PR to fix this?

**Comment by haishengwu-okta** [comment]
+1 
for me when one of dependencies failed to be install (like `ffi`), the task will ignore the error and complete successfully.
