### ISSUE TITLE
I'm linting x scss files, but on success i get "1 file is lint free" message

### ISSUE THREAD

**Issue by webfeature** [ahmednuaman/grunt-scss-lint#123]
The message "1 file is lint free" is confusing if you are linting x scss files (x > 1), because sometimes the grunt tasks is throwing the same message, although the linting fails ([#122](https://github.com/ahmednuaman/grunt-scss-lint/issues/122)).

I think, it would be helpful to get the real number of linted files.

Regrads,
Christian

**Comment by ahmednuaman** [comment]
Sure, create a PR?
