### ISSUE TITLE
Update README to reflect new Gem name

### ISSUE THREAD

**Issue by chrisnicotera** [ahmednuaman/grunt-scss-lint#125]
The newly-maintained version of this project is now publishing its Gem under the name `scss_lint` (with an underscore, which your Gemfile correctly reflects :)). The `scss-lint` Gem can still be used, but it is out of date and missing some new features.

I edited the README to reflect this information in pull request https://github.com/ahmednuaman/grunt-scss-lint/pull/124.

**Comment by ahmednuaman** [comment]
Thanks, will look at the PR.
