### ISSUE TITLE
task fails on scss-lint version 0.31.0

### ISSUE THREAD

**Issue by swar30** [ahmednuaman/grunt-scss-lint#91]
On my env (both dev and ci) grunt-scss-lint started to fail once I got the new version of scss-lint 0.31.0 which shipped a few days ago

It fails with message

	Running "scsslint:styles" (scsslint) task
	Verifying property scsslint.styles exists in config...OK
	Files: app/_bootstrapImport.scss -> styles
	Options: config=".scss-lint.yml", reporterOutput=null, bundleExec, colorizeOutput, compact, force=false, maxBuffer=307200
	scss-lint options: config=".scss-lint.yml", reporterOutput=null, bundleExec, colorizeOutput, compact, force=false, maxBuffer=307200
	Running scss-lint on styles
	>> scss-lint failed with error code: 66
	>> and the following message:Error: Command failed:
	Warning: Task "scsslint:styles" failed. Use --force to continue.

If I restrict scss-lint to <=0.30.0 than it works perfectly ok

**Comment by ahmednuaman** [comment]
Ok, closing.
