### ISSUE TITLE
GitHub and NPM task.js differ

### ISSUE THREAD

**Issue by tbremer** [ahmednuaman/grunt-scss-lint#95]
I am not totally sure how this happened, but the NPM and GitHub task.js file are out of sync.

I made branch until I realized @thomasphorton #82 fixed this.

When pulling from NPM `npm install --save-dev grunt-scss-lint` the `tasks/scss-lint.js` file has the incorrect default config option, whereas when cloning from GitHub, it is correct. Image attached.

The only thing I can think to do is bump the version number and repush to NPM? Or, revert current version number, push, add current version back, push again.

Anyone else see this?

![config-github-npm](https://cloud.githubusercontent.com/assets/2998575/6091344/3c3e35ee-ae6d-11e4-946d-5f3fb563db53.png)

**Comment by ahmednuaman** [comment]
Yo sorry about that, it seems I didn't make a release with that new config. Eg compare master to https://github.com/ahmednuaman/grunt-scss-lint/blob/7a38ff6263f5b3f087a0d814561740178b4296bd/tasks/scss-lint.js
